name: prevenso_app_front
description: "A new Flutter project."

publish_to: 'none'

version: 2.0.1+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0

  http: ^1.2.1
  provider: ^6.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.2
  intl: ^0.20.2

  path_provider: ^2.1.3
  open_file: ^3.3.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: false
  windows:
    generate: true
    icon_size: 48
  image_path: "launcher_icon/logo.png"