name: prevenso_app_front
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # Para hacer llamadas HTTP
  http: ^1.4.0

  # Para la gestión de estado (simple y potente)
  provider: ^6.1.5

  # Para el manejo de errores funcionales (Either)
  dartz: ^0.10.1

  # Para comparar objetos fácilmente
  equatable: ^2.0.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  flutter_lints: ^6.0.0
  path_provider: ^2.1.1
  open_file: ^3.3.2
  open_filex: ^4.4.0
  permission_handler: ^12.0.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - shorebird.yaml