name: prevenso_app_front
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- DEPENDENCIAS DE EJECUCIÓN (Piezas del coche) ---
  http: ^1.2.1
  provider: ^6.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.2
  intl: ^0.20.2

  # --- CAMBIO CLAVE: Se mueven los plugins a la sección correcta ---
  path_provider: ^2.1.3
  open_file: ^3.3.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- DEPENDENCIAS DE DESARROLLO (Herramientas del garaje) ---
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/